### ISSUE TITLE
error when i run python3 Assemble.py

### ISSUE THREAD

**Issue by deleep225** [degiacom/assemble#7]
python3 Assemble_GUI.py

Traceback (most recent call last):
  File "/home/dhileep/softwares/assemble-master_1/assemble-master/Assemble_GUI.py", line 1218, in <module>
    frame = MainWindow(None, "Assemble!")
  File "/home/dhileep/softwares/assemble-master_1/assemble-master/Assemble_GUI.py", line 62, in __init__
    self.S=SystemOut(self)
  File "/home/dhileep/softwares/assemble-master_1/assemble-master/Assemble_GUI.py", line 785, in __init__
    buttons.Add(self.lblsystem, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 3  )
wx._core.wxAssertionError: C++ assertion "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT)))" failed at /tmp/pip-install-q0_akk_c/wxpython_a93f3073dbec427d942f01246377be7f/ext/wxWidgets/src/common/sizer.cpp(2267) in DoInsert(): wxALIGN_RIGHT will be ignored in this sizer: only vertical alignment flags can be used in horizontal sizers

DO NOT PANIC !!

If you're an end user running a program not developed by you, please ignore this message, it is harmless, and please try reporting the problem to the program developers.

You may also set WXSUPPRESS_SIZER_FLAGS_CHECK environment variable to suppress all such checks when running this program.

If you're the developer, simply remove this flag from your code to avoid getting this message. You can also call wxSizerFlags::DisableConsistencyChecks() to globally disable all such checks, but this is strongly not recommended.

**Comment by preposterousboast** [comment]
Hi!

This is definitely not a timely answer, but if anyone else encounters this error, here's how to fix it:

- Set an environment variable WXSUPPRESS_SIZER_FLAGS_CHECK as mentioned in the error text by typing the following into the command line:
                                    $env:WXSUPPRESS_SIZER_FLAGS_CHECK = 'WXSUPPRESS_SIZER_FLAGS_CHECK'
- Run the Assemble_GUI.py again. The UI will appear.

The variable needs to be set every time you open the PowerShell anew, so save this somewhere for quick access.
